Numpy is a shorthand form of "Numeric Python" or "Numerical Python" and it is pronounced as (Num-pee).\

To perform large mathematical operations and statistical operations Numpy is an incredible library.

Numpy is basically a simple programming language that works superbly well for the multi-dimensional arrays and matrices multiplication.

In [284]:
from platform import python_version 
print(python_version())

3.9.13


In [285]:
import numpy as np
print(np.__version__)

1.21.5


In [286]:
import numpy as np

# numpy String functions:  np.char.FunctionName(array) :
The numpy.char module provides a set of vectorized string operations for arrays of type numpy.str_ or numpy.bytes_

 islower(),find(),count(), replace(),splitlines(),add(),multiply(),center(),join(),split(),title(),lower(),isupper(),isnumeric() ,isalpha(),index(),startswith(),isspace(),isdigit(),isdecimal(),upper(),capitalize(),swapcase(),strip(),char.partition()    

In [287]:
array2 = np.array(['apple',  'Cherry262',523,  'banana','watermelon','cherry','apple'," ",'Pineapple' , "SSSS ! " ] )
print(array2)
print(type(array2))

['apple' 'Cherry262' '523' 'banana' 'watermelon' 'cherry' 'apple' ' '
 'Pineapple' 'SSSS ! ']
<class 'numpy.ndarray'>


In [288]:
print("title****:    ",np.char.title(array2))  #convert an input string into a title cased version.
print("istitle****:   ",np.char.istitle(array2)) #returns true if input is a title cased string(start with capital follwerd by lowercase letters)
print("isdigit****:    ",np.char.isdigit(array2))

print("count****:    ",np.char.count(array2,'apple'))
print("countsum****:    ",np.char.count(array2,'apple').sum())
print("count****:    ",np.char.count('apple',array2))
print("countsum****:    ",np.char.count('apple',array2).sum())

print("capitalize****:  ",np.char.capitalize(array2))
print("Swapcase****:    ",np.char.swapcase(array2)) #convert lowercase into uppercase and uppercase into lowercase
print("strip****:    ",np.char.strip(array2)) #removes extra spaces
print("Sort****:  ",np.sort(array2))
print("splitlines****:  ",np.char.splitlines(array2))

title****:     ['Apple' 'Cherry262' '523' 'Banana' 'Watermelon' 'Cherry' 'Apple' ' '
 'Pineapple' 'Ssss ! ']
istitle****:    [False  True False False False False False False  True False]
isdigit****:     [False False  True False False False False False False False]
count****:     [1 0 0 0 0 0 1 0 1 0]
countsum****:     3
count****:     [1 0 0 0 0 0 1 0 0 0]
countsum****:     2
capitalize****:   ['Apple' 'Cherry262' '523' 'Banana' 'Watermelon' 'Cherry' 'Apple' ' '
 'Pineapple' 'Ssss ! ']
Swapcase****:     ['APPLE' 'cHERRY262' '523' 'BANANA' 'WATERMELON' 'CHERRY' 'APPLE' ' '
 'pINEAPPLE' 'ssss ! ']
strip****:     ['apple' 'Cherry262' '523' 'banana' 'watermelon' 'cherry' 'apple' ''
 'Pineapple' 'SSSS !']
Sort****:   [' ' '523' 'Cherry262' 'Pineapple' 'SSSS ! ' 'apple' 'apple' 'banana'
 'cherry' 'watermelon']
splitlines****:   [list(['apple']) list(['Cherry262']) list(['523']) list(['banana'])
 list(['watermelon']) list(['cherry']) list(['apple']) list([' '])
 list(['Pineapple']) list(['SS

In [289]:
array2

array(['apple', 'Cherry262', '523', 'banana', 'watermelon', 'cherry',
       'apple', ' ', 'Pineapple', 'SSSS ! '], dtype='<U11')

In [290]:
print("islower:    ",np.char.islower(array2))
print("isupper:     ",np.char.isupper(array2)) #True if all the characters of the string element are in uppercase.
print("isnumeric:   ",np.char.isnumeric(array2))
print("isdecimal:   ",np.char.isdecimal(array2))
print("Find:   ",np.char.find(array2,"apple")) # 0 if found,-1 not found, 4 for from 4th index it was found
print("Replace:  ",np.char.replace(array2,"banana","Banana"))

print("startswith:  ",np.char.startswith(array2,"a"))
print("endsswith:  ",np.char.endswith(array2,"e"))

print("isspace:    ",np.char.isspace(array2)) #true if none/emplty value is given
print("upper:  ",np.char.upper(array2))

islower:     [ True False False  True  True  True  True False False False]
isupper:      [False False False False False False False False False  True]
isnumeric:    [False False  True False False False False False False False]
isdecimal:    [False False  True False False False False False False False]
Find:    [ 0 -1 -1 -1 -1 -1  0 -1  4 -1]
Replace:   ['apple' 'Cherry262' '523' 'Banana' 'watermelon' 'cherry' 'apple' ' '
 'Pineapple' 'SSSS ! ']
startswith:   [ True False False False False False  True False False False]
endsswith:   [ True False False False False False  True False  True False]
isspace:     [False False False False False False False  True False False]
upper:   ['APPLE' 'CHERRY262' '523' 'BANANA' 'WATERMELON' 'CHERRY' 'APPLE' ' '
 'PINEAPPLE' 'SSSS ! ']


#  Mathematical functions: or Rounding Decimals
  ceil(),floor(), trunc(), fix()  ,around() ,round() 

In [291]:
arr = np.array([-3.1666, 3.6667,1.6454654655])
x=np.trunc(arr)      # numpy.trunc() used to return the truncated integer value of the input array elements. or used to round 
                            #the array values to the nearest integers towards zero.
print(x)

[-3.  3.  1.]


In [292]:
x=np.fix(arr) # used to round the array values to the nearest integers towards zero.
print(x) 

[-3.  3.  1.]


In [293]:
#round an array to the given number of decimal
x=np.around(arr) #around(arr,dedcimal=0,out=None0)
print(x)

x=np.around(arr,1)
print(x)

x=np.round(arr) # round an array to the given number of decimal # round(arr,dedcimal=0,out=None0)
print(x)

[-3.  4.  2.]
[-3.2  3.7  1.6]
[-3.  4.  2.]


In [294]:
x=np.floor(3.1666) #rounds off decimal to nearest lowest interger. datatype=FLoat
print("Floor:",x)

x=np.ceil(3.166) #rounds off decimal to nearest upper interger. datatype=FLoat
print("Ceil:",x)

Floor: 3.0
Ceil: 4.0


#  Statistical  functions
  amin(),amax(),median(),mean(),std()    

In [295]:
a = np.array([[2,15,20],[80,43,31],[22,43,10]]) 
print(a)
#axis = 0 means along the column and axis = 1 means working along the row.
print("\nThe minimum element among the array:",np.amin(a))  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("\nThe minimum element among the columns of array",np.amin(a,1))  

[[ 2 15 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2

The minimum element among the rows of array [ 2 15 10]

The minimum element among the columns of array [ 2 31 10]


In [296]:
a = np.array([[2,15,20],[80,43,31],[22,43,10]])  
print("\nThe minimum element among the array:",np.amax(a)) 
#axis = 0 means along the column and axis = 1 means working along the row.
print("\nThe minimum element among the rows of array",np.amax(a,0))  
print("\nThe minimum element among the columns of array",np.amax(a,1))  


The minimum element among the array: 80

The minimum element among the rows of array [80 43 31]

The minimum element among the columns of array [20 80 43]


In [297]:
x= np.array([80, 23, 17, 1, 39] )
print("The mean of the array[80, 23, 17, 1, 39] : ",np.mean(x))

p = np.array([[14, 19, 12, 34, 43], [16, 8, 28, 8, 20], [25, 5, 55, 1, 2]] )
print("MultiDimensionalArray:\n",p)
# calculating mean of the flattened array 
print("\nThe mean of the array when axis = None : ") #axis = 0 means along the column and axis = 1 means working along the row.
print(np.mean(p)) 
print("\nThe mean of the array when axis = 0: ")
print(np.mean(p, axis = 0)) 
print("\nThe mean of the array when axis = 1 : ")
print(np.mean(p, axis = 1)) 

The mean of the array[80, 23, 17, 1, 39] :  32.0
MultiDimensionalArray:
 [[14 19 12 34 43]
 [16  8 28  8 20]
 [25  5 55  1  2]]

The mean of the array when axis = None : 
19.333333333333332

The mean of the array when axis = 0: 
[18.33333333 10.66666667 31.66666667 14.33333333 21.66666667]

The mean of the array when axis = 1 : 
[24.4 16.  17.6]


In [298]:
x=np.array( [80, 23, 17, 1, 39] )
print("The median of the array[80, 23, 17, 1, 39] :",np.median(x)) #Thus this function returns the median of the array elements as an output.

inp = np.array([[1, 17, 19, 33, 49], [14, 6, 87, 8, 19], [34, 2, 54, 4, 7]] )
print("Array:\n",inp)
print("Median:",np.median(inp)) 

# calculating median along the axis = 0 
print("\nThe median of array when axis = 0 : ")#axis = 0 means along the column and axis = 1 means working along the row.
print(np.median(inp, axis = 0)) 

#calculating median along the axis = 1 
print("\nThe median of array when axis = 1 : ")
print(np.median(inp, axis = 1)) 


The median of the array[80, 23, 17, 1, 39] : 23.0
Array:
 [[ 1 17 19 33 49]
 [14  6 87  8 19]
 [34  2 54  4  7]]
Median: 17.0

The median of array when axis = 0 : 
[14.  6. 54.  8. 19.]

The median of array when axis = 1 : 
[19. 14.  7.]


In [299]:
# standard deviation.
a = np.array([[11, 2], [13, 44]])
print("The array is:\n",a)
print("Standard Deviation is :",np.std(a))
print("Standard Deviation along axis 0:")
print(np.std(a, axis=0))
print("Standard Deviation along axis 1:")
print(np.std(a, axis=1))

The array is:
 [[11  2]
 [13 44]]
Standard Deviation is : 15.850867484147358
Standard Deviation along axis 0:
[ 1. 21.]
Standard Deviation along axis 1:
[ 4.5 15.5]


# =============numpy basic operations============

# Array Methods:
# Array :
    Python does not have built-in support for Arrays, but Python Lists can be used instead.In Python you will have to 
    import a library, like the NumPy library.\
    
ordered , mutable ,Allows duplicates\
allows Slicing\
arrAy can have more than 1 null values\
Arrays are used to store multiple values in one single variable\


nditer(),ndenumerate()                     : loop through array\
,copy(),view(),base(),\
shape(),reshape(),\
append(),concatenate(), stack(),hstack(),vstack()                 : join arrays\
array_split(), \
where() and searchsorted(),                  : search \
sort(),\
np.flipud(),np.flip(),-np.sort(-array)   : reverse an arrya\
random.randint(), random.rand(), random.choice(), random.shuffle(), random.permutation(),           : random number\
lcm(), \
  gcd().reduce(),\
add(),subtract(),multiply(),divide(), power(),mod(),remainder(),absolute(),prod(),        :  arithmetic functions\
trunc(),fix(),around(),floor(),ceil()         :Rounding Decimals\
diff() 

In [300]:

array2=np.array(['apple','banana','watermelon','cherry','apple'])

In [301]:
array2

array(['apple', 'banana', 'watermelon', 'cherry', 'apple'], dtype='<U10')

# numpy.char.index():
return the index of substring,If not found raise a ValueError\
numpy.char.index(a, sub, start=0, end=None)


In [302]:
ar1=np.array(['I love Python']) 
output1 = np.char.index(ar1,'love') 
print ( output1)

[2]


# np.char.find()
char.find(a, sub, start=0, end=None)


In [303]:
array2

array(['apple', 'banana', 'watermelon', 'cherry', 'apple'], dtype='<U10')

In [304]:
print(np.char.find(array2, sub ='a') ) 
print(np.char.find(array2,'apple') )
print(np.char.find(array2, 'water') )
#0 for exact match
#1 if present
#-1 not present 
# other digits represent starting position of substring  Ex.apple in pineapple     o/p : 4


[ 0  1  1 -1  0]
[ 0 -1 -1 -1  0]
[-1 -1  0 -1 -1]


# np.append() and np.concatenate()

In [305]:
x=np.append("pineapple",array2) #insert new string at first position
y=np.append(array2,"pineapple") #insert new string at the end position
x,y

(array(['pineapple', 'apple', 'banana', 'watermelon', 'cherry', 'apple'],
       dtype='<U10'),
 array(['apple', 'banana', 'watermelon', 'cherry', 'apple', 'pineapple'],
       dtype='<U10'))

In [306]:
print(np.concatenate((array2,[10])))  #insert new string at end
print(np.concatenate(([10],array2)))#insert new string at begining 

['apple' 'banana' 'watermelon' 'cherry' 'apple' '10']
['10' 'apple' 'banana' 'watermelon' 'cherry' 'apple']


In [307]:
n=np.array(["14","5","6"])
n1=np.array([1,5,6])
np.append(n,n1)

array(['14', '5', '6', '1', '5', '6'], dtype='<U11')

# count()
syntax=  np.core.defchararray.count(arr,substring,start=0,end=none)\
substring=substring to search for\
start or end : range to search in

In [308]:
array2

array(['apple', 'banana', 'watermelon', 'cherry', 'apple'], dtype='<U10')

In [309]:
np.char.count(array2,'apple')

array([1, 0, 0, 0, 1])

In [310]:
np.char.count(array2,'a')

array([1, 3, 1, 0, 1])

In [311]:
np.char.count(array2,'a',start=1,end=3)

array([0, 1, 1, 0, 0])

# np.reshape()
changiging the shape (dimension) of an array

In [312]:
np.arange(12) #array of 12 elemnts start from 0 to 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [313]:
np.arange(12).reshape(4,3)  # 2D array which consist of 4 array with 3  elemnts in each.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [314]:
np.arange(12).reshape(2,2,3) # #2 arrays that contains 2 arrays, each with 3 elements

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [315]:
import numpy as np

In [316]:
a=np.array([1,2,3,2,7,5,10,3]) #array
a*2

array([ 2,  4,  6,  4, 14, 10, 20,  6])

# numpy.insert() 
numpy.insert(arr, obj, values, axis=None)[source]

In [317]:
np.insert(a,4,2) # at 4th  index insert 2

array([ 1,  2,  3,  2,  2,  7,  5, 10,  3])

# numpy.append() 
To append new value at the end\
numpy.append(arr, values, axis=None)


In [318]:
np.append(a,4)

array([ 1,  2,  3,  2,  7,  5, 10,  3,  4])

# np.unique()

In [319]:
np.unique(a)  #return unique values 

array([ 1,  2,  3,  5,  7, 10])

# numpy.delete()
numpy.delete(arr, obj, axis=None)

In [320]:
a

array([ 1,  2,  3,  2,  7,  5, 10,  3])

In [321]:
np.delete(a,2) # delete the value at index 2

array([ 1,  2,  2,  7,  5, 10,  3])

In [322]:
a

array([ 1,  2,  3,  2,  7,  5, 10,  3])

In [323]:
b=[1,2,3]      #list
b*2

[1, 2, 3, 1, 2, 3]

# Reverse the array

In [324]:
a11=np.array(['aa','bb','vv','ff'])
np.flip(a11)   

array(['ff', 'vv', 'bb', 'aa'], dtype='<U2')

In [325]:
print(a)

[ 1  2  3  2  7  5 10  3]


In [326]:
np.flip(a)     #reverse the array

array([ 3, 10,  5,  7,  2,  3,  2,  1])

In [327]:
np.flipud(a)     #reverse the array

array([ 3, 10,  5,  7,  2,  3,  2,  1])

In [328]:
-np.sort(-a) #sort then reverse

array([10,  7,  5,  3,  3,  2,  2,  1])

In [329]:
np.sort(a) [::-1]   #sort then reverse

array([10,  7,  5,  3,  3,  2,  2,  1])

# sort numpy array:

In [330]:
print(np.sort(a,axis=-1))

[ 1  2  2  3  3  5  7 10]


In [331]:
print(np.sort(a))

[ 1  2  2  3  3  5  7 10]


In [332]:
asort=np.array(['sss','aa','df','frs','gsr'])
print(np.sort(asort))
print(np.sort(asort)[::-1])

['aa' 'df' 'frs' 'gsr' 'sss']
['sss' 'gsr' 'frs' 'df' 'aa']


In [333]:
print(np.sort(a)[::-1]) #sort then reverse

[10  7  5  3  3  2  2  1]


In [334]:
print(-np.sort(-a)) #only for digit array   #sort then reverse

[10  7  5  3  3  2  2  1]


In [335]:
print(np.sort(-a))

[-10  -7  -5  -3  -3  -2  -2  -1]


In [336]:
print(-np.sort(a))

[ -1  -2  -2  -3  -3  -5  -7 -10]


In [337]:
#crating array
#array contains duplicate values and 
#can have more than one null values adn arrays are ordered
car00=np.array(["Hyundai","","volvo","BMW","","BMW",""]) 
print(car00)

['Hyundai' '' 'volvo' 'BMW' '' 'BMW' '']


In [338]:
#indexing 
print(car00)
print(car00[0])
print(type(car00))
print(car00[0][0])
print(car00[0][1])
print(car00[0][3])

print("from volvo:",car00[2][3])

['Hyundai' '' 'volvo' 'BMW' '' 'BMW' '']
Hyundai
<class 'numpy.ndarray'>
H
y
n
from volvo: v


In [339]:
#array allows slicing
ary=np.array([[1,2,3],[7,5,10]])
print("array:\n",ary)
print("************")
print(ary[:,:1])
print("************")
print(ary[:2])
print("************")
print(ary[:1,:3]) 
print("************")
print(ary[:1,0:2])

array:
 [[ 1  2  3]
 [ 7  5 10]]
************
[[1]
 [7]]
************
[[ 1  2  3]
 [ 7  5 10]]
************
[[1 2 3]]
************
[[1 2]]


In [340]:
#array are mutable: can make change in list add/remove/edit
car00[1]="GT360"
car00

array(['Hyundai', 'GT360', 'volvo', 'BMW', '', 'BMW', ''], dtype='<U7')

In [341]:
car00[4]="ferrari"
print(car00)

['Hyundai' 'GT360' 'volvo' 'BMW' 'ferrari' 'BMW' '']


In [342]:
car00[6]="Maruti"
car00

array(['Hyundai', 'GT360', 'volvo', 'BMW', 'ferrari', 'BMW', 'Maruti'],
      dtype='<U7')

# Looping-/iterating through array

In [343]:
car00

array(['Hyundai', 'GT360', 'volvo', 'BMW', 'ferrari', 'BMW', 'Maruti'],
      dtype='<U7')

Looping through 1D array 

In [344]:
for x in car00:  #1D array
    print(x)
    

Hyundai
GT360
volvo
BMW
ferrari
BMW
Maruti


In [345]:
x=0
while x<len(car00): #1D array
    print(car00[x])
    x=x+1

Hyundai
GT360
volvo
BMW
ferrari
BMW
Maruti


In [346]:
print(len(car00))


7


In [347]:
for x in range(len(car00)): #1D array
    print(car00[x])  

Hyundai
GT360
volvo
BMW
ferrari
BMW
Maruti


Comprehensions in Python provide us with a short and concise way to construct new sequences (such as lists, set, dictionary etc.)

In [348]:
a=[print(x) for x in car00]       #array comprehension #1D array

Hyundai
GT360
volvo
BMW
ferrari
BMW
Maruti


In [349]:
a2=[print(x)  for x in car00  if x !="BMW" ]     #array  Comprehension

Hyundai
GT360
volvo
ferrari
Maruti


In [350]:
a3=[print(x)  for x in car00  if "a" in x]

Hyundai
ferrari
Maruti


Looping through 2D array 

In [351]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:   
    for y in x:print(y)

1
2
3
4
5
6


In [352]:
x=0
while x<len(arr): #1D array
    print(arr[x])
    x=x+1

[1 2 3]
[4 5 6]


Looping through 3D array

In [353]:
arr = np.array([[[1, 2, 3], [4, 5, 6]] , [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [354]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)
#or
#for x in np.nditer(arr):
#  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using np.nditer(array)


In [355]:
arr = np.array([1, 2,3,4])
for x in np.nditer(arr):
  print(x)

1
2
3
4


In [356]:
arr = np.array([[[1, 2], [3, 4]], [["x","gs"], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
x
gs
7
8


# Enumerated Iteration Using np.ndenumerate(array)
Enumeration means mentioning sequence number of somethings one by one.\
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.



In [357]:
arr = np.array([1, 2, 3])
for x in np.ndenumerate(arr):
  print( x)


((0,), 1)
((1,), 2)
((2,), 3)


In [358]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.ndenumerate(arr):
  print( x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


In [359]:
arr = np.array([ [[1, 2, 3], [5, 6, 7]], [[10,20,30] ,[40,50,60]] ])

for  idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(1, 0, 0) 10
(1, 0, 1) 20
(1, 0, 2) 30
(1, 1, 0) 40
(1, 1, 1) 50
(1, 1, 2) 60


In [360]:
arr = np.array([ [[1, 2, 3], [5, 6, 7]], [[10,20,30] ,[40,50,60]] ])

for  x in np.ndenumerate(arr):
  print(x)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 5)
((0, 1, 1), 6)
((0, 1, 2), 7)
((1, 0, 0), 10)
((1, 0, 1), 20)
((1, 0, 2), 30)
((1, 1, 0), 40)
((1, 1, 1), 50)
((1, 1, 2), 60)


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

 1)  0-D Arrays:\
 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [361]:
a0=np.array(42)
print(a0)
print(a0.ndim) #return the number of dimensions of an array
print("***********")
a0=np.array((42,5,5))
print(a0)
print(a0.ndim) #return the number of dimensions of an array

42
0
***********
[42  5  5]
1


2) 1-D Arrays\
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [362]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(a1.ndim) #return the number of dimensions of an array

[1 2 3 4 5]
1


3)2-D Arrays\
An array that has 1-D arrays as its elements is called a 2-D array.


In [363]:
a2 = np.array([ [1, 2, 3], [4, 5 ,6] ])
print(a2)
print(a2.ndim) #return the number of dimensions of an array

[[1 2 3]
 [4 5 6]]
2


4) 3-D arrays\
An array that has 2-D arrays (matrices) as its elements is called 3-D array

In [364]:
a3 = np.array( [[[1, 2, 3,4,5,6]]])
print(a3)
print(a3.ndim) #return the number of dimensions of an array

[[[1 2 3 4 5 6]]]
3


In [365]:
a3 = np.array( [[[1, 2, 3], [4, 5, 6]]  ,  [[1, 2, 3], [4, 5, 6]]  ])
print(a3)
print('******')
print(a3.ndim) #return the number of dimensions of an array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
******
3


Higher Dimensional Arrays\
An array can have any number of dimensions.


ndmin: used to create an array of higher dimensions \
ndim : used to return the number of dimensions of an array

In [366]:
ar0=np.array([1,2,3,4],ndmin=6) # ndmin
print(ar0)
print(ar0.ndim) #return the number of dimensions of an array

[[[[[[1 2 3 4]]]]]]
6


# Array Indexing

Indexing: Indexing is used to obtain individual elements. \
Slicing: Slicing is used to obtain a sequence of elements.

In [367]:
print(car00)

['Hyundai' 'GT360' 'volvo' 'BMW' 'ferrari' 'BMW' 'Maruti']


In [368]:
print(car00[0])
print(car00[-2]) #indexinng in negative start from -1
print(car00[1][3]) #1D array
print(car00[-1][-3]) #1D array
print(car00[1][-3]) #1D array

Hyundai
BMW
6
u
3


In [369]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #2D array [,]
print( arr[0, 1])
print( arr[1, -1])
print( arr[-1, 3])
print( arr[-2, -1])

2
10
9
5


In [370]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #2D array
print( arr[1, 1]) 
print( arr[-2, 1]) 
print( arr[1, -3]) 
print( arr[-1, -1]) 

7
2
8
10


In [371]:
arr = np.array([ [[1, 2, 3], [4, 5, 6]] , [[7, 8, 9], [10, 11, 12]]  ])  #3D array [, ,]
print(arr[0, 1, 2])
print(arr[1, 1, 0]) 
print(arr[1, 1, -2]) 
print(arr[0, -1, -2]) 
print(arr[-2,-2, -2]) 
print(arr[0:1]) 

6
10
11
5
2
[[[1 2 3]
  [4 5 6]]]


# Array Slicing
array[start:end:step]

With slicing, we can easily access elements in the array. It can be done on one or more dimensions of a NumPy array. Note: When we slice arrays, the start index is inclusive but the stop index is exclusive. In NumPy, it's possible to access the portion of an array using the slicing operator ' : '

In [372]:
#              [0 ,1 ,2 ,3 ,4 ,5 ,6]
#              [-7,-6,-5,-4,-3,-2-,-1]

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])         #5 is not consider, n-1=5-1=4 so the indexing ends with 4
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

print(arr[1:5:2])  #with steps .5 is not considerd, n-1=5-1=4 so the indexing ends with 4
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [373]:
#                 [   0        ,         1]
#               [[0,1, 2, 3, 4], [0, 1, 2, 3, 4]]

#                 [   -2       ,         -1]
#             [[-5,-4,-3,-2-,-1],-5,-4,-3,-2-,-1]]

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])    #4=4-1=3
print("**************")
print(arr[0:2, 2]) # 2nd element from both indexs
print("**************")
print(arr[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included)

[7 8 9]
**************
[3 8]
**************
[[2 3 4]
 [7 8 9]]


In [374]:
arr = np.array([ [[1, 2, 3, 4], [6, 7, 8, 9]] , [[10,20,30,40],[50,60,70,80]] ])
arr

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [375]:
print(arr[1,1:2])    # [array ,row,column]
print(arr.dtype)

[[50 60 70 80]]
int32


In [376]:
print(arr[1, 1:2,1:2])  # [array ,row,column]
print(arr.dtype)

[[60]]
int32


In [377]:
print(arr[0, 0:2,1:3])    # [array ,row,column]
print(arr.dtype)

[[2 3]
 [7 8]]
int32


# Arry DataType

In [378]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(a1.dtype)

[1 2 3 4 5]
int32


Create an array with data type string:


In [379]:
arr = np.array([1, 2, 3, 4], dtype="S") #string
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Create an array with data type 4 bytes integer:

In [380]:
arr = np.array([1, 2, 3, 4], dtype='i') #int
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [381]:
arr = np.array([1, 2, 3, 4], dtype='i4') #int with 4 byte
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [382]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
#we convert integer array into string but cannot convert string into integer

#arr = np.array(['a', '2', '3'], dtype='i')
#print(arr.dtype)

Change data type from float to integer by using 'i' or "int" as parameter value:



In [383]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i') # or rr.astype('int')
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


Change data type from integer to boolean:


In [384]:
print(arr)
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[ True  True  True]
bool


# copy() vs view()

copy is a new array, and the view is just a view of the original array.

The copy() owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view() does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [385]:
arr

array([1.1, 2.1, 3.1])

In [386]:
arr = np.array([1, 2, 3, 4, 5]) #original array
x=arr.copy()   # does not make change in original array
arr[0] = 42
print("original array :",arr)
print("x:",x)

original array : [42  2  3  4  5]
x: [1 2 3 4 5]


In [387]:
arr = np.array([1, 2, 3, 4, 5]) #original arrayarr
print("original array",arr)
x=arr.view() #make change in original array
arr[0] = 42
print("original array after view() :",arr)
print("x :",x)

original array [1 2 3 4 5]
original array after view() : [42  2  3  4  5]
x : [42  2  3  4  5]


Check if Array Owns its Data?\
Every NumPy array has the attribute base that returns None if the array owns the data.

In [388]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view() 
#None if the array owns the data.
#return list if array does not own its own data

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape:
The shape of an array is the number of elements in each dimension.\
also return count of row and  columns  in dataframe 

In [389]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print("\n",arr.shape) #2 dimensions, with 4 elements

[[1 2 3 4]
 [5 6 7 8]]

 (2, 4)


In [390]:
arr = np.array([1, 2, 3, 4], ndmin=5) #ndmin
print(arr)
print(arr.ndim) # ndim
print('shape of array :', arr.shape) # last dimension i.e 5th dimension with 4 element

[[[[[1 2 3 4]]]]]
5
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping
Reshaping means changing the shape of an array.\
The shape of an array is the number of elements in each dimension.\
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [391]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  #1D to 2D  array
print(arr.shape)
newarr = arr.reshape(4, 3) #an array that contain 4 arrays , each with 3 elements
print(newarr)
print(newarr.ndim)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [392]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  #1D to 3D  array
newarr = arr.reshape(2,3,2) #arrya that contain 2 arrays and that contains 3 arrays each, each with 2 elements  
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Unknown Dimension\
You are allowed to have one "unknown" dimension.\
Pass -1 as the value, and NumPy will calculate this number for you.

In [393]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)
print("Shape:",newarr.shape)
print("ndim:",newarr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
ndim: 3


In [394]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [395]:
#Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


# Joining NumPy Arrays

concatenate(),stack(),vstack(),hstack()

In [396]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [397]:
#Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print("arr1:\n",arr1)
print("arr2:\n",arr2)
print("\nOutput:\n",arr)

arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]

Output:
 [[1 2 5 6]
 [3 4 7 8]]


In [398]:
#Join two 2-D arrays along col (axis=0):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print("arr1:\n",arr1)
print("arr2:\n",arr2)
print("\n Output:\n",arr)

arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]

 Output:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [399]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [400]:
#using stack()

In [401]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [402]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


using hstack()\
hstack() to stack along rows.

horizontal: _

In [403]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]



vstack()  to stack along columns
vertical : |

In [404]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


dstack()\
dstack() to stack along height, which is the same as depth.

In [405]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array
Splitting is reverse operation of Joining.\
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.\
np.array_split(array,size)

In [406]:
arr = np.array([1, 2, 3, 4, 5, 6]) 
newarr=np.array_split(arr,3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [407]:
#2D array

In [408]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [409]:
print(newarr[0],"\n")
print(newarr[1],"\n")
print(newarr[2],"\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]
 [11 12]] 



In [410]:
#Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [411]:
print(newarr[2],"\n")

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]] 



# Searching Arrays
used to selecting elements or values based on a conditoin, and return the indexes that get a match.\
where() : if condition is true return index \
syntax=np.where(condition,[if true],[if false ])

searchsorted() : used to find the index where element should be inserted \
np.searchsorted(arr,valueToInsert,side='left',sorter=none) : used to find the indices where element should be inserted to maintain an order.

In [412]:
arrsrh=np.array(['sss','aaa','Fef','ersg','afe'])

x1=np.where(arrsrh=='aaa')
print(x1)

x1=np.where(arrsrh=='a')
print(x1)

(array([1], dtype=int64),)
(array([], dtype=int64),)


In [413]:
y=np.where(arrsrh=='sss',True,False)
y

array([ True, False, False, False, False])

In [414]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x=np.where(arr==4) #index of value 4 , index starts from 0
print(x)

(array([3, 5, 6], dtype=int64),)


In [415]:
"""
for x in arr:
    if x>3 :
        print(x)
    else:
        print(x*5) #or
"""

np.where(arr>3,arr,5*arr) #values that are >3 keep as it is else multiply*5   np.where(condition,true,false )

array([ 5, 10, 15,  4,  5,  4,  4])

In [416]:
l=[10,20,30,40,50,40]
print(np.where(l==10))

s=np.array(l)
print(np.where(s==10))

for x in l:
    if x==10 :
        print("present")

(array([], dtype=int64),)
(array([0], dtype=int64),)
present


In [417]:

x = np.where(arr%2 == 0)
print(x)

x1 = np.where(arr%2 == 1)
print(x1)


(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


np.searchsorted(arr,valueToInsert,side='left',sorter=none) : used to find the indices where element should be inserted to maintain an order.

In [418]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.searchsorted(arr, 7) 
print(x)

7


In [419]:
arr = np.array([2,6,7,8,9,1])
x = np.searchsorted(arr,4) 
print(x)

1


In [420]:
arr = np.array([6,7,8,9,1])
x = np.searchsorted(arr,1) 
print(x)
y = np.searchsorted(arr,[10,-10,2],side='right') 
print(y)
y1 = np.searchsorted(arr,[10,-10,2,3,40],side='left') 
print(y1)

0
[5 0 0]
[5 0 0 0 5]


In [421]:
#Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7,side='right') 
print(x)

2


In [422]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [423]:
arr = np.array([10, 55, 71])
x = np.searchsorted(arr, [20, 44, 60])
print(x)

[1 1 2]


# Sorting Arrays
sort()

In [424]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) #asc
print(np.sort(arr)[::-1]) #desc

[0 1 2 3]
[3 2 1 0]


In [425]:
arr = np.array([True, False, True]) #Sort a boolean array:
print(np.sort(arr))


[False  True  True]


In [426]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]




# Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.



In [427]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x] #will only return true elements
print(newarr)

[41 43]


In [428]:
arr = np.array([41, 42, 43, 44])
filter_arr = []  # Create an empty list

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [429]:
arr = np.array([41, 42, 43, 44])
filter_arr = []  # Create an empty list

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True]
[42 44]


In [430]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [431]:
filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False  True False  True]
[42 44]


# Random Number

from numpy import random\
random.randint(): random integer value \
random.rand():  random float value \
The choice() generate a random value from given array of value. takes array as parameter 

In [432]:
from numpy import random 
random.randint(100) # any random number from 1-100

9

In [433]:
x=random.randint(100, size=5) # 5 random integers.
print(x)

[32  0 36 71  2]


In [434]:
x = random.rand()
print(x)

0.7584477651237047


In [435]:
x = random.rand(5) # 5 random float no.
print(x)

[0.24729868 0.40431227 0.9366944  0.80536597 0.35844045]


In [436]:
x=random.choice([1,5,6,8]) #a random element from your choice of an array
print(x)
x1=random.choice([1,5,6,8.5]) #a random element from your choice of an array
print(x1)

8
5.0


In [437]:
x=random.choice([1,5,6,8],size=3) # 3random element from your  an array
x

array([1, 5, 8])

In [438]:
x = random.choice([3, 5, 7, 9], size=(3, 5)) # an array that contains 3 array of 5 elements
print(x)

[[7 5 5 7 5]
 [9 7 5 3 3]
 [5 7 9 9 5]]


# Random Permutations
shuffle():A permutation refers to an arrangement of elements.method makes changes to the original array.\
permutation():A permutation refers to an arrangement of elements.leaves the original array un-changed

In [439]:
arr = np.array([1, 2, 3, 4, 5])
#x= random.shuffle(arr)
print("Original Array before shuffle:",arr)
print("x:",random.shuffle(arr))
print("Original Array after shuffle:",arr)

Original Array before shuffle: [1 2 3 4 5]
x: None
Original Array after shuffle: [1 4 2 3 5]


In [440]:
arr = np.array([1, 4, 5,2,3])
print("Original before shuffle:",arr)
x=random.permutation(arr)
print("x:",x)
print("Original Array after shuffle:",arr)

Original before shuffle: [1 4 5 2 3]
x: [3 5 2 4 1]
Original Array after shuffle: [1 4 5 2 3]


# Finding LCM
NumPy LCM Lowest Common Multiple: np.lcm()

In [441]:
import numpy as np
"""
 2| 4  6
 2| 2  3     ====> 2*2*3=12
 3| 1  3
  | 1  1
"""    
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


# NumPy GCD Greatest Common Denominator
np.gcd(): Greatest Common Denominator\
np.gcd.reduce():Highest Common Factor (hcf)

In [442]:
"""
2|12   2| 42 
2|6    3|21    ====>common Divisor=3*2=6
3|3    7|7 
 |1     |1

"""
num1 = 12
num2 = 42
x = np.gcd(num1, num2) #To find the greatest/Highest Common Factor(hcf) , you can use the reduce() method.
print(x)


6


In [443]:
#or
arr = np.array([12,42])
x = np.gcd.reduce(arr)  #To find the greatest/Highest Common Factor(hcf) of all values in an array, you can use the reduce() method.
print(x)

6


In [444]:
arr = np.array([20, 8, 32, 36, 12])
x = np.gcd.reduce(arr) #To find the Highest Common Factor(hcf) , you can use the reduce() method.
print(x)
y= np.gcd([20, 8],[18,36]) #To find the Highest Common Factor(hcf) , you can use the reduce() method.
print(y)

4
[2 4]


In [445]:
arr = np.array([20, 8, 32, 36, 11])
x = np.gcd.reduce(arr) #To find the Highest Common Factor(hcf) , you can use the reduce() method.
print(x)

1


# Simple Arithmetic
add(),subtract(),multiply(),divide(),power(),mod(),remainder(),
absolute(),prod(),\
all functions takes 2 or 3 arguments

In [446]:
np.add(10, 5)

15

In [447]:
arr1 = np.array([10, 11, 12, 13, 14, 15]) 
arr2 = np.array([20, 21, 22, 23, 24, 25])

In [448]:
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [449]:
print(np.subtract(10, 5))
newarr = np.subtract(arr1, arr2)
print(newarr)

5
[-10 -10 -10 -10 -10 -10]


In [450]:
newarr = np.multiply(arr1, arr2)
print(newarr)

[200 231 264 299 336 375]


In [451]:
print(arr1 )
print(arr2)

[10 11 12 13 14 15]
[20 21 22 23 24 25]


In [452]:
newarr = np.divide(arr1, arr2)
print(newarr)

newarr = np.divide(arr2, arr1)
print(newarr)
print("**************************")
newarr = np.divide(0, 10) #0
print(newarr)

newarr = np.divide(10, 0) #divide by zero warning
print(newarr)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]
**************************
0.0
inf


C:\Users\pujad\AppData\Local\Temp\ipykernel_22912\3150279859.py:10: RuntimeWarning: divide by zero encountered in true_divide
  newarr = np.divide(10, 0) #divide by zero warning


In [453]:
 #function rises the values from the first array to the power of the values of the second array,
    #and return the results in a new array.
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)
print("pow(20,5)::",pow(20,5))

[      1000    3200000  729000000 -520093696       2500          0]
pow(20,5):: 3200000


In [454]:
10**3,  20**5

(1000, 3200000)

Both the mod() and the remainder() functions return the remainder of the values in
the first array corresponding to the values in the second array

In [455]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

In [456]:
newarr = np.mod(arr1, arr2) #remainder 
print(newarr)

[ 1  6  3  0  0 27]


In [457]:
newarr = np.remainder(arr1, arr2) #remainder 
print(newarr)

[ 1  6  3  0  0 27]


In [458]:
newarr = np.divmod(arr1, arr2)# Return the quotient and mod(mod=reminder):
print(newarr) 

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [459]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr) #-ve into +
print(newarr)

[1 2 1 2 3 4]


In [460]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [461]:
#Returns: 24 because 1*2*3*4 = 24
arr = np.array([1, 2, 3, 4]) #multiply all values
x = np.prod(arr) #product of all the elements
print(x)

24


In [462]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2]) #product of all the elements

print(x)

40320


In [463]:
1*2*3*4*5*6*7*8

40320



# NumPy Differences: diff()

A discrete difference means subtracting two successive elements.
E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

In [464]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
newarr #Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20

array([  5,  10, -20])